---
- name: install and configure mosquitto with mqtt listener over tls
  hosts: all
  become: yes

  tasks:
  - name: ensure epel is enabled
    yum:
      name: epel-release
      state: present

  - name: install packages
    yum:
      name: mosquitto
      state: present
