---
- name: install and configure mosquitto with mqtt listener over tls with pki
  hosts: all
  become: yes

  vars:
    mosquitto_fqdn: mosquitto.example.com
    clients:
      - client-1.example.com
      - client-2.example.com
      - client-3.example.com

  roles:
    - mosquitto
