- name: check if easyrsa is already present
  ansible.builtin.stat:
    path: "{{ easyrsa_script }}"
  register: easyrsa

- name: ensure easyrsa project gpg key is present
  ansible.builtin.command: gpg --recv-keys "{{ easyrsa_gpg_key_id }}"
  when: not easyrsa.stat.exists

- name: ensure easyrsa source and signature are present
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/tmp"
  with_items:
  - "https://github.com/OpenVPN/easy-rsa/releases/download/v{{ easyrsa_version }}/{{ easyrsa_directory_name }}.tgz"
  - "https://github.com/OpenVPN/easy-rsa/releases/download/v{{ easyrsa_version }}/{{ easyrsa_directory_name }}.tgz.sig"
  when: not easyrsa.stat.exists

- name: verify tarball signature and install
  command: "gpg --verify {{ easyrsa_directory_name }}.tgz.sig {{ easyrsa_directory_name }}.tgz"
  args:
    chdir: /tmp
  register: easyrsa_tarball_verified
  when: not easyrsa.stat.exists

- name: extract easyrsa tarball
  ansible.builtin.unarchive:
    src: "/tmp/{{ easyrsa_directory_name }}.tgz"
    dest: /usr/local/src
    owner: root
    group: root
    remote_src: yes
  when: not easyrsa.stat.exists and easyrsa_tarball_verified
