- name: ensure easyrsa is present
  ansible.builtin.include_tasks:
    file: easyrsa.yaml

- name: initialize private key infrastructure
  command: |
    /usr/local/src/EasyRSA-3.1.5/easyrsa --batch init-pki
  args:
    chdir: "/root"
    creates: "/root/pki"

- name: initialize private key infrastructure
  command: |
    /usr/local/src/EasyRSA-3.1.5/easyrsa --batch build-ca nopass
  args:
    chdir: "/root"
    creates: "/root/pki/ca.crt"

- name: generate server certificate
  ansible.builtin.command: /usr/local/src/EasyRSA-3.1.5/easyrsa --batch build-server-full "{{ mosquitto_fqdn }}" nopass
  args:
    chdir: "/root"
    creates: "/root/pki/issued/{{ mosquitto_fqdn }}.crt"

- name: generate client certificates
  ansible.builtin.command: /usr/local/src/EasyRSA-3.1.5/easyrsa --batch build-client-full "{{ item }}" nopass
  args:
    chdir: "/root"
    creates: "/root/pki/issued/{{ item }}.crt"
  loop: "{{ clients }}"
