- name: ensure easyrsa is present
  ansible.builtin.include_tasks:
    file: easyrsa.yaml

- name: initialize public key infrastructure
  command: "{{ easyrsa_script }} --batch init-pki"
  args:
    chdir: "/root"
    creates: "/root/pki"

- name: initialize certificate authority
  command: "{{ easyrsa_script }} --batch build-ca nopass"
  args:
    chdir: "/root"
    creates: "/root/pki/ca.crt"

- name: generate server certificate
  ansible.builtin.command: "{{ easyrsa_script }} --batch build-server-full {{ mosquitto_fqdn }} nopass"
  args:
    chdir: "/root"
    creates: "/root/pki/issued/{{ mosquitto_fqdn }}.crt"

- name: generate client certificates
  ansible.builtin.command: "{{ easyrsa_script }} --batch build-client-full {{ item }} nopass"
  args:
    chdir: "/root"
    creates: "/root/pki/issued/{{ item }}.crt"
  loop: "{{ clients }}"

- name: update certificate revocation list
  command: "{{ easyrsa_script }} --batch gen-crl"
  args:
    chdir: "/root"
